# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from thingsboard_client.api.widgets_bundle_controller_api import WidgetsBundleControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestWidgetsBundleControllerApi(unittest.TestCase):
    """WidgetsBundleControllerApi unit test stubs"""

    def setUp(self):
        self.api = WidgetsBundleControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_widgets_bundle_using_delete(self):
        """Test case for delete_widgets_bundle_using_delete

        deleteWidgetsBundle  # noqa: E501
        """
        pass

    def test_get_widgets_bundle_by_id_using_get(self):
        """Test case for get_widgets_bundle_by_id_using_get

        getWidgetsBundleById  # noqa: E501
        """
        pass

    def test_get_widgets_bundles_using_get(self):
        """Test case for get_widgets_bundles_using_get

        getWidgetsBundles  # noqa: E501
        """
        pass

    def test_get_widgets_bundles_using_get1(self):
        """Test case for get_widgets_bundles_using_get1

        getWidgetsBundles  # noqa: E501
        """
        pass

    def test_save_widgets_bundle_using_post(self):
        """Test case for save_widgets_bundle_using_post

        saveWidgetsBundle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
