# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from api.billing_controller_api import BillingControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestBillingControllerApi(unittest.TestCase):
    """BillingControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.billing_controller_api.BillingControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_billing_cycle_using_post(self):
        """Test case for create_billing_cycle_using_post

        createBillingCycle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
