# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from models.time_page_data_dashboard_info import TimePageDataDashboardInfo  # noqa: E501
from thingsboard_client.rest import ApiException


class TestTimePageDataDashboardInfo(unittest.TestCase):
    """TimePageDataDashboardInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimePageDataDashboardInfo(self):
        """Test TimePageDataDashboardInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thingsboard_client.models.time_page_data_dashboard_info.TimePageDataDashboardInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
