# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from thingsboard_client.api.audit_log_controller_api import AuditLogControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestAuditLogControllerApi(unittest.TestCase):
    """AuditLogControllerApi unit test stubs"""

    def setUp(self):
        self.api = AuditLogControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_audit_logs_by_customer_id_using_get(self):
        """Test case for get_audit_logs_by_customer_id_using_get

        getAuditLogsByCustomerId  # noqa: E501
        """
        pass

    def test_get_audit_logs_by_entity_id_using_get(self):
        """Test case for get_audit_logs_by_entity_id_using_get

        getAuditLogsByEntityId  # noqa: E501
        """
        pass

    def test_get_audit_logs_by_user_id_using_get(self):
        """Test case for get_audit_logs_by_user_id_using_get

        getAuditLogsByUserId  # noqa: E501
        """
        pass

    def test_get_audit_logs_using_get(self):
        """Test case for get_audit_logs_using_get

        getAuditLogs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
