# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from thingsboard_client.api.alarm_controller_api import AlarmControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestAlarmControllerApi(unittest.TestCase):
    """AlarmControllerApi unit test stubs"""

    def setUp(self):
        self.api = AlarmControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ack_alarm_using_post(self):
        """Test case for ack_alarm_using_post

        ackAlarm  # noqa: E501
        """
        pass

    def test_clear_alarm_using_post(self):
        """Test case for clear_alarm_using_post

        clearAlarm  # noqa: E501
        """
        pass

    def test_delete_alarm_using_delete(self):
        """Test case for delete_alarm_using_delete

        deleteAlarm  # noqa: E501
        """
        pass

    def test_get_alarm_by_id_using_get(self):
        """Test case for get_alarm_by_id_using_get

        getAlarmById  # noqa: E501
        """
        pass

    def test_get_alarm_info_by_id_using_get(self):
        """Test case for get_alarm_info_by_id_using_get

        getAlarmInfoById  # noqa: E501
        """
        pass

    def test_get_alarms_using_get(self):
        """Test case for get_alarms_using_get

        getAlarms  # noqa: E501
        """
        pass

    def test_get_highest_alarm_severity_using_get(self):
        """Test case for get_highest_alarm_severity_using_get

        getHighestAlarmSeverity  # noqa: E501
        """
        pass

    def test_save_alarm_using_post(self):
        """Test case for save_alarm_using_post

        saveAlarm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
