# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from models.attributes_entity_view import AttributesEntityView  # noqa: E501
from thingsboard_client.rest import ApiException


class TestAttributesEntityView(unittest.TestCase):
    """AttributesEntityView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributesEntityView(self):
        """Test AttributesEntityView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thingsboard_client.models.attributes_entity_view.AttributesEntityView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
