# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from thingsboard_client.api.auth_controller_api import AuthControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestAuthControllerApi(unittest.TestCase):
    """AuthControllerApi unit test stubs"""

    def setUp(self):
        self.api = AuthControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_user_using_post(self):
        """Test case for activate_user_using_post

        activateUser  # noqa: E501
        """
        pass

    def test_change_password_using_post(self):
        """Test case for change_password_using_post

        changePassword  # noqa: E501
        """
        pass

    def test_check_activate_token_using_get(self):
        """Test case for check_activate_token_using_get

        checkActivateToken  # noqa: E501
        """
        pass

    def test_check_reset_token_using_get(self):
        """Test case for check_reset_token_using_get

        checkResetToken  # noqa: E501
        """
        pass

    def test_get_user_using_get(self):
        """Test case for get_user_using_get

        getUser  # noqa: E501
        """
        pass

    def test_request_reset_password_by_email_using_post(self):
        """Test case for request_reset_password_by_email_using_post

        requestResetPasswordByEmail  # noqa: E501
        """
        pass

    def test_reset_password_using_post(self):
        """Test case for reset_password_using_post

        resetPassword  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
