# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from api.device_controller_api import DeviceControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestDeviceControllerApi(unittest.TestCase):
    """DeviceControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.device_controller_api.DeviceControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_device_to_customer_using_post(self):
        """Test case for assign_device_to_customer_using_post

        assignDeviceToCustomer  # noqa: E501
        """
        pass

    def test_assign_device_to_public_customer_using_post(self):
        """Test case for assign_device_to_public_customer_using_post

        assignDeviceToPublicCustomer  # noqa: E501
        """
        pass

    def test_delete_device_using_delete(self):
        """Test case for delete_device_using_delete

        deleteDevice  # noqa: E501
        """
        pass

    def test_find_by_query_using_post1(self):
        """Test case for find_by_query_using_post1

        findByQuery  # noqa: E501
        """
        pass

    def test_get_customer_devices_using_get(self):
        """Test case for get_customer_devices_using_get

        getCustomerDevices  # noqa: E501
        """
        pass

    def test_get_device_by_id_using_get(self):
        """Test case for get_device_by_id_using_get

        getDeviceById  # noqa: E501
        """
        pass

    def test_get_device_credentials_by_device_id_using_get(self):
        """Test case for get_device_credentials_by_device_id_using_get

        getDeviceCredentialsByDeviceId  # noqa: E501
        """
        pass

    def test_get_device_types_using_get(self):
        """Test case for get_device_types_using_get

        getDeviceTypes  # noqa: E501
        """
        pass

    def test_get_devices_by_ids_using_get(self):
        """Test case for get_devices_by_ids_using_get

        getDevicesByIds  # noqa: E501
        """
        pass

    def test_get_tenant_device_using_get(self):
        """Test case for get_tenant_device_using_get

        getTenantDevice  # noqa: E501
        """
        pass

    def test_save_device_credentials_using_post(self):
        """Test case for save_device_credentials_using_post

        saveDeviceCredentials  # noqa: E501
        """
        pass

    def test_save_device_using_post(self):
        """Test case for save_device_using_post

        saveDevice  # noqa: E501
        """
        pass

    def test_unassign_device_from_customer_using_delete(self):
        """Test case for unassign_device_from_customer_using_delete

        unassignDeviceFromCustomer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
