# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from thingsboard_client.api.admin_controller_api import AdminControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestAdminControllerApi(unittest.TestCase):
    """AdminControllerApi unit test stubs"""

    def setUp(self):
        self.api = AdminControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_updates_using_get(self):
        """Test case for check_updates_using_get

        checkUpdates  # noqa: E501
        """
        pass

    def test_get_admin_settings_using_get(self):
        """Test case for get_admin_settings_using_get

        getAdminSettings  # noqa: E501
        """
        pass

    def test_save_admin_settings_using_post(self):
        """Test case for save_admin_settings_using_post

        saveAdminSettings  # noqa: E501
        """
        pass

    def test_send_test_mail_using_post(self):
        """Test case for send_test_mail_using_post

        sendTestMail  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
