# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thingsboard_client
from api.widget_type_controller_api import WidgetTypeControllerApi  # noqa: E501
from thingsboard_client.rest import ApiException


class TestWidgetTypeControllerApi(unittest.TestCase):
    """WidgetTypeControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.widget_type_controller_api.WidgetTypeControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_widget_type_using_delete(self):
        """Test case for delete_widget_type_using_delete

        deleteWidgetType  # noqa: E501
        """
        pass

    def test_get_bundle_widget_types_using_get(self):
        """Test case for get_bundle_widget_types_using_get

        getBundleWidgetTypes  # noqa: E501
        """
        pass

    def test_get_widget_type_by_id_using_get(self):
        """Test case for get_widget_type_by_id_using_get

        getWidgetTypeById  # noqa: E501
        """
        pass

    def test_get_widget_type_using_get(self):
        """Test case for get_widget_type_using_get

        getWidgetType  # noqa: E501
        """
        pass

    def test_save_widget_type_using_post(self):
        """Test case for save_widget_type_using_post

        saveWidgetType  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
